services:
  vault:
    image: hashicorp/vault:1.15.2
    container_name: vault-server
    hostname: vault.local
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
#      VAULT_LOCAL_CONFIG: |
#        storage "file" {
#          path = "/vault/data"
#        }
#        listener "tcp" {
#          address     = "0.0.0.0:8200"
#          tls_cert_file = "/vault/certs/vault-server.crt"
#          tls_key_file  = "/vault/certs/vault-server.key"
#          tls_client_ca_file = "/vault/certs/ca.crt"
#          tls_require_and_verify_client_cert = false
#          tls_disable_client_certs = false
#        }
#        api_addr = "https://vault.local:8200"
#        ui = true
#        disable_mlock = true
#        log_level = "Info"
    ports:
      - "8200:8200"
    volumes:
      - ./data:/vault/data:rw
      - ./certs:/vault/certs:ro
      - ./config:/vault/config:ro
    networks:
      vault-network:
        ipv4_address: 172.20.0.10
    command: ["vault", "server", "-config=/vault/config/vault.hcl"]
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  vault-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
